### ISSUE TITLE
Compatibility with Angular 15

### ISSUE THREAD

**Issue by maxailloud** [halloverden/ngx-zendesk-web-widget#1]
Are there any plans for a compatibility with Angular 15?

**Comment by erichjsonfosse** [comment]
@maxailloud 
Definitely, although not on the top of the list at the moment. If you have the time, we'd love to see a pull request :)

**Comment by luluanacarla** [comment]
any updates here?

**Comment by maxailloud** [comment]
Unfortunately we are phasing out of using zendesk so I don't think I'm going to have time to work on this anymore.
